In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import zipfile

### Loading the data

In [3]:
zf = zipfile.ZipFile('loan.zip')

In [4]:
date_mon_yy = lambda x: pd.datetime.strptime(x, '%d-%B-%y')

In [5]:
loans_df = pd.read_csv(zf.open(zipfile.ZipFile.namelist(zf)[0]),parse_dates=True)

D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
len(loans_df.columns)

111

In [7]:
loans_df.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,3.971700e+04,3.971700e+04,39717.000000,39717.000000,39717.000000,39717.000000,3.971700e+04,39717.000000,39717.000000,39717.000000,...,0.0,0.0,0.0,0.0,39020.000000,39678.0,0.0,0.0,0.0,0.0
mean,6.831319e+05,8.504636e+05,11219.443815,10947.713196,10397.448868,324.561922,6.896893e+04,13.315130,0.146512,0.869200,...,NaN,NaN,NaN,NaN,0.043260,0.0,NaN,NaN,NaN,NaN
std,2.106941e+05,2.656783e+05,7456.670694,7187.238670,7128.450439,208.874874,6.379377e+04,6.678594,0.491812,1.070219,...,NaN,NaN,NaN,NaN,0.204324,0.0,NaN,NaN,NaN,NaN
min,5.473400e+04,7.069900e+04,500.000000,500.000000,0.000000,15.690000,4.000000e+03,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
25%,5.162210e+05,6.667800e+05,5500.000000,5400.000000,5000.000000,167.020000,4.040400e+04,8.170000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
50%,6.656650e+05,8.508120e+05,10000.000000,9600.000000,8975.000000,280.220000,5.900000e+04,13.400000,0.000000,1.000000,...,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
75%,8.377550e+05,1.047339e+06,15000.000000,15000.000000,14400.000000,430.780000,8.230000e+04,18.600000,0.000000,1.000000,...,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
max,1.077501e+06,1.314167e+06,35000.000000,35000.000000,35000.000000,1305.190000,6.000000e+06,29.990000,11.000000,8.000000,...,NaN,NaN,NaN,NaN,2.000000,0.0,NaN,NaN,NaN,NaN

In [8]:
total_rows = loans_df.shape[0]

### % of missing fields

In [9]:
round((loans_df.isna().sum()/total_rows)*100,2)

id                                  0.00
member_id                           0.00
loan_amnt                           0.00
funded_amnt                         0.00
funded_amnt_inv                     0.00
term                                0.00
int_rate                            0.00
installment                         0.00
grade                               0.00
sub_grade                           0.00
emp_title                           6.19
emp_length                          2.71
home_ownership                      0.00
annual_inc                          0.00
verification_status                 0.00
issue_d                             0.00
loan_status                         0.00
pymnt_plan                          0.00
url                                 0.00
desc                               32.58
purpose                             0.00
title                               0.03
zip_code                            0.00
addr_state                          0.00
dti                                 0.00
delinq_2yrs                         0.00
earliest_cr_line                    0.00
inq_last_6mths                      0.00
mths_since_last_delinq             64.66
mths_since_last_record             92.99
                                   ...
mo_sin_old_rev_tl_op              100.00
mo_sin_rcnt_rev_tl_op             100.00
mo_sin_rcnt_tl                    100.00
mort_acc                          100.00
mths_since_recent_bc              100.00
mths_since_recent_bc_dlq          100.00
mths_since_recent_inq             100.00
mths_since_recent_revol_delinq    100.00
num_accts_ever_120_pd             100.00
num_actv_bc_tl                    100.00
num_actv_rev_tl                   100.00
num_bc_sats                       100.00
num_bc_tl                         100.00
num_il_tl                         100.00
num_op_rev_tl                     100.00
num_rev_accts                     100.00
num_rev_tl_bal_gt_0               100.00
num_sats                          100.00
num_tl_120dpd_2m                  100.00
num_tl_30dpd                      100.00
num_tl_90g_dpd_24m                100.00
num_tl_op_past_12m                100.00
pct_tl_nvr_dlq                    100.00
percent_bc_gt_75                  100.00
pub_rec_bankruptcies                1.75
tax_liens                           0.10
tot_hi_cred_lim                   100.00
total_bal_ex_mort                 100.00
total_bc_limit                    100.00
total_il_high_credit_limit        100.00
Length: 111, dtype: float64

### Removing the columns whose values are null

In [10]:
loans_df1 = loans_df.dropna(axis=1,how='all')

#### after removing null columns finally we got 57 columns

In [11]:
len(loans_df1.columns)

57

In [12]:
round((loans_df1.isna().sum()/loans_df1.shape[0])*100,2)

id                             0.00
member_id                      0.00
loan_amnt                      0.00
funded_amnt                    0.00
funded_amnt_inv                0.00
term                           0.00
int_rate                       0.00
installment                    0.00
grade                          0.00
sub_grade                      0.00
emp_title                      6.19
emp_length                     2.71
home_ownership                 0.00
annual_inc                     0.00
verification_status            0.00
issue_d                        0.00
loan_status                    0.00
pymnt_plan                     0.00
url                            0.00
desc                          32.58
purpose                        0.00
title                          0.03
zip_code                       0.00
addr_state                     0.00
dti                            0.00
delinq_2yrs                    0.00
earliest_cr_line               0.00
inq_last_6mths                 0.00
mths_since_last_delinq        64.66
mths_since_last_record        92.99
open_acc                       0.00
pub_rec                        0.00
revol_bal                      0.00
revol_util                     0.13
total_acc                      0.00
initial_list_status            0.00
out_prncp                      0.00
out_prncp_inv                  0.00
total_pymnt                    0.00
total_pymnt_inv                0.00
total_rec_prncp                0.00
total_rec_int                  0.00
total_rec_late_fee             0.00
recoveries                     0.00
collection_recovery_fee        0.00
last_pymnt_d                   0.18
last_pymnt_amnt                0.00
next_pymnt_d                  97.13
last_credit_pull_d             0.01
collections_12_mths_ex_med     0.14
policy_code                    0.00
application_type               0.00
acc_now_delinq                 0.00
chargeoff_within_12_mths       0.14
delinq_amnt                    0.00
pub_rec_bankruptcies           1.75
tax_liens                      0.10
dtype: float64

### next_pyment_d is 97% empty

In [13]:
loans_df1.next_pymnt_d.value_counts()

Jun-16    1125
Jul-16      15
Name: next_pymnt_d, dtype: int64

### Next payment (upcomming) column doesnt need so droping off.

In [14]:
loans_df1.drop(columns='next_pymnt_d',axis=1,inplace=True)

D:\Anaconda3\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [15]:
round((loans_df1.isna().sum()/loans_df1.shape[0])*100,2)

id                             0.00
member_id                      0.00
loan_amnt                      0.00
funded_amnt                    0.00
funded_amnt_inv                0.00
term                           0.00
int_rate                       0.00
installment                    0.00
grade                          0.00
sub_grade                      0.00
emp_title                      6.19
emp_length                     2.71
home_ownership                 0.00
annual_inc                     0.00
verification_status            0.00
issue_d                        0.00
loan_status                    0.00
pymnt_plan                     0.00
url                            0.00
desc                          32.58
purpose                        0.00
title                          0.03
zip_code                       0.00
addr_state                     0.00
dti                            0.00
delinq_2yrs                    0.00
earliest_cr_line               0.00
inq_last_6mths                 0.00
mths_since_last_delinq        64.66
mths_since_last_record        92.99
open_acc                       0.00
pub_rec                        0.00
revol_bal                      0.00
revol_util                     0.13
total_acc                      0.00
initial_list_status            0.00
out_prncp                      0.00
out_prncp_inv                  0.00
total_pymnt                    0.00
total_pymnt_inv                0.00
total_rec_prncp                0.00
total_rec_int                  0.00
total_rec_late_fee             0.00
recoveries                     0.00
collection_recovery_fee        0.00
last_pymnt_d                   0.18
last_pymnt_amnt                0.00
last_credit_pull_d             0.01
collections_12_mths_ex_med     0.14
policy_code                    0.00
application_type               0.00
acc_now_delinq                 0.00
chargeoff_within_12_mths       0.14
delinq_amnt                    0.00
pub_rec_bankruptcies           1.75
tax_liens                      0.10
dtype: float64

In [16]:
loans_df1.loc['revol_util'] =loans_df1.revol_util.apply(lambda x: float(str(x).replace('%','')))

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [17]:
loans_df1.loc['term'] =loans_df1.term.apply(lambda x: str(x).replace('months','').strip())

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

### Catagerical column: 'emp_length' re-arranging to range as per definition

In [18]:
loans_df1.emp_length.value_counts()/total_rows

10+ years    0.223557
< 1 year     0.115391
2 years      0.110482
3 years      0.103104
4 years      0.086512
5 years      0.082635
1 year       0.081577
6 years      0.056122
7 years      0.044641
8 years      0.037238
9 years      0.031674
Name: emp_length, dtype: float64

In [19]:
loans_df1.emp_length.unique()

array(['10+ years', '< 1 year', '1 year', '3 years', '8 years', '9 years',
       '4 years', '5 years', '6 years', '2 years', '7 years', nan],
      dtype=object)

### Creating dict for emp_length

In [20]:
## 0-1, 1-9,10+, na
## corr the title company..... revisit
emp_len_dict = {k:'0-10 years' for k in loans_df1.emp_length.unique()}
emp_len_dict['n/a']='n/a'
emp_len_dict['10+ years'] = '10+ years'
emp_len_dict['< 1 year']='0 years'


print(emp_len_dict)

{'10+ years': '10+ years', '< 1 year': '0 years', '1 year': '0-10 years', '3 years': '0-10 years', '8 years': '0-10 years', '9 years': '0-10 years', '4 years': '0-10 years', '5 years': '0-10 years', '6 years': '0-10 years', '2 years': '0-10 years', '7 years': '0-10 years', nan: '0-10 years', 'n/a': 'n/a'}

### Replacing nan to 'n/a' for emp_length

In [21]:
loans_df1.emp_length.fillna('n/a',inplace=True,axis=0)

D:\Anaconda3\lib\site-packages\pandas\core\generic.py:5434: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [22]:
loans_df1['emp_length_range'] = loans_df1.emp_length.map(emp_len_dict)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [23]:
loans_df1['emp_length_range'].unique()

array(['10+ years', '0 years', '0-10 years', 'n/a'], dtype=object)

In [24]:
(loans_df1.emp_length_range.value_counts()/total_rows)*100

0-10 years    63.398545
10+ years     22.355666
0 years       11.539139
n/a            2.711685
Name: emp_length_range, dtype: float64

#### from above emp_lenght % , n/a is 2% of total row's. so it can ignore

In [25]:
loanData = loans_df1.copy()

In [26]:
loanData.drop(columns=['url'],axis=1,inplace=True)

In [27]:
loanData.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'pymnt_plan', 'desc', 'purpose', 'title',
       'zip_code', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record',
       'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'policy_code', 'application_type',
       'acc_now_delinq', 'chargeoff_within_12_mths', 'delinq_amnt',
       'pub_rec_bankruptcies', 'tax_liens', 'emp_length_range'],
      dtype='object')

### convert to date

In [28]:
col_date =['issue_d','last_pymnt_d','last_credit_pull_d']

In [29]:
loanData['issue_d'].head(20)

0     Dec-11
1     Dec-11
2     Dec-11
3     Dec-11
4     Dec-11
5     Dec-11
6     Dec-11
7     Dec-11
8     Dec-11
9     Dec-11
10    Dec-11
11    Dec-11
12    Dec-11
13    Dec-11
14    Dec-11
15    Dec-11
16    Dec-11
17    Dec-11
18    Dec-11
19    Dec-11
Name: issue_d, dtype: object

In [30]:
loanData['issue_d'] = pd.to_datetime(loanData['issue_d'],format='%b-%y')

In [31]:
loanData.corr()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,...,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,pub_rec_bankruptcies,tax_liens
id,1.000000,0.993650,0.141919,0.152286,0.249547,0.086587,0.008731,0.095983,-0.008644,-0.042378,...,0.033426,-0.013359,0.122365,NaN,NaN,NaN,NaN,NaN,-0.009505,NaN
member_id,0.993650,1.000000,0.140710,0.150322,0.257887,0.081025,0.009380,0.096963,-0.008119,-0.047086,...,0.031565,-0.015155,0.123627,NaN,NaN,NaN,NaN,NaN,-0.008769,NaN
loan_amnt,0.141919,0.140710,1.000000,0.981578,0.940034,0.930288,0.271149,0.066439,-0.031864,0.009229,...,0.135446,0.072853,0.448742,NaN,NaN,NaN,NaN,NaN,-0.037180,NaN
funded_amnt,0.152286,0.150322,0.981578,1.000000,0.958422,0.956159,0.266965,0.066283,-0.032355,0.009259,...,0.136284,0.074676,0.453133,NaN,NaN,NaN,NaN,NaN,-0.038502,NaN
funded_amnt_inv,0.249547,0.257887,0.940034,0.958422,1.000000,0.905039,0.254375,0.074689,-0.038501,-0.005712,...,0.123759,0.060358,0.442604,NaN,NaN,NaN,NaN,NaN,-0.042746,NaN
installment,0.086587,0.081025,0.930288,0.956159,0.905039,1.000000,0.270874,0.054186,-0.019657,0.009722,...,0.118152,0.075467,0.401688,NaN,NaN,NaN,NaN,NaN,-0.034103,NaN
annual_inc,0.008731,0.009380,0.271149,0.266965,0.254375,0.270874,1.000000,-0.122732,0.023083,0.033908,...,0.021589,0.015604,0.140401,NaN,NaN,NaN,NaN,NaN,-0.016801,NaN
dti,0.095983,0.096963,0.066439,0.066283,0.074689,0.054186,-0.122732,1.000000,-0.034452,0.001405,...,0.024878,0.011033,0.005212,NaN,NaN,NaN,NaN,NaN,0.005691,NaN
delinq_2yrs,-0.008644,-0.008119,-0.031864,-0.032355,-0.038501,-0.019657,0.023083,-0.034452,1.000000,0.008091,...,0.012315,0.013912,-0.012149,NaN,NaN,NaN,NaN,NaN,0.003375,NaN
inq_last_6mths,-0.042378,-0.047086,0.009229,0.009259,-0.005712,0.009722,0.033908,0.001405,0.008091,1.000000,...,0.018972,0.012420,0.028514,NaN,NaN,NaN,NaN,NaN,0.016346,NaN
mths_since_last_delinq,0.117193,0.122963,0.014871,0.016359,0.071924,0.000047,-0.008822,0.068815,-0.569438,-0.003851,...,-0.008622,-0.018697,0.007023,NaN,NaN,NaN,NaN,NaN,0.025841,NaN
mths_since_last_record,0.702130,0.719538,0.004968,-0.006059,0.437906,-0.062171,-0.031866,0.187175,-0.036628,-0.027878,...,-0.013125,-0.038484,0.078624,NaN,NaN,NaN,NaN,NaN,0.823352,NaN
open_acc,0.020388,0.017928,0.177168,0.175530,0.163027,0.172812,0.158200,0.288045,0.011656,0.091713,...,0.016396,0.006219,0.078865,NaN,NaN,NaN,NaN,NaN,0.005930,NaN
pub_rec,-0.019440,-0.018721,-0.051236,-0.052169,-0.053214,-0.046532,-0.018689,-0.004621,0.007463,0.024802,...,-0.005521,-0.005536,-0.032214,NaN,NaN,NaN,NaN,NaN,0.847305,NaN
revol_bal,0.008763,0.005113,0.317597,0.310392,0.290797,0.312679,0.279961,0.228743,-0.055125,-0.022381,...,0.042091,0.022400,0.120371,NaN,NaN,NaN,NaN,NaN,-0.049406,NaN
total_acc,0.042149,0.044374,0.256442,0.250589,0.242854,0.230824,0.235771,0.229881,0.067892,0.111499,...,0.023281,0.010551,0.162841,NaN,NaN,NaN,NaN,NaN,-0.011807,NaN
out_prncp,0.180619,0.170743,0.192937,0.194941,0.203688,0.125082,0.033573,0.036095,-0.003008,-0.012106,...,-0.018878,-0.011394,-0.066393,NaN,NaN,NaN,NaN,NaN,-0.010024,NaN
out_prncp_inv,0.180591,0.170706,0.192623,0.194675,0.203693,0.124932,0.033472,0.036012,-0.003203,-0.011780,...,-0.018858,-0.011382,-0.066324,NaN,NaN,NaN,NaN,NaN,-0.010314,NaN
total_pymnt,0.140045,0.139975,0.886613,0.903160,0.881228,0.856928,0.257980,0.064766,-0.022695,-0.010559,...,0.023950,0.024555,0.474624,NaN,NaN,NaN,NaN,NaN,-0.043661,NaN
total_pymnt_inv,0.220838,0.229307,0.854243,0.870799,0.913257,0.817416,0.247119,0.071647,-0.028976,-0.020277,...,0.017862,0.015016,0.462255,NaN,NaN,NaN,NaN,NaN,-0.047011,NaN
total_rec_prncp,0.112213,0.112168,0.852021,0.870255,0.845848,0.850773,0.259571,0.041316,-0.038795,-0.023433,...,-0.094821,-0.058634,0.543408,NaN,NaN,NaN,NaN,NaN,-0.054125,NaN
total_rec_int,0.172856,0.173234,0.729726,0.737469,0.730914,0.634725,0.185476,0.106071,0.023077,0.021774,...,0.075552,0.033289,0.191990,NaN,NaN,NaN,NaN,NaN,-0.003609,NaN
total_rec_late_fee,-0.055082,-0.057750,0.044706,0.046705,0.027172,0.056709,0.006243,-0.011781,0.030609,0.031215,...,0.099925,0.093178,-0.060600,NaN,NaN,NaN,NaN,NaN,-0.005489,NaN
recoveries,0.033426,0.031565,0.135446,0.136284,0.123759,0.118152,0.021589,0.024878,0.012315,0.018972,...,1.000000,0.796816,-0.069955,NaN,NaN,NaN,NaN,NaN,-0.004651,NaN
collection_recovery_fee,-0.013359,-0.015155,0.072853,0.074676,0.060358,0.075467,0.015604,0.011033,0.013912,0.012420,...,0.796816,1.000000,-0.041874,NaN,NaN,NaN,NaN,NaN,-0.005208,NaN
last_pymnt_amnt,0.122365,0.123627,0.448742,0.453133,0.442604,0.401688,0.140401,0.005212,-0.012149,0.028514,...,-0.069955,-0.041874,1.000000,NaN,NaN,NaN,NaN,NaN,-0.022585,NaN
collections_12_mths_ex_med,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
policy_code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acc_now_delinq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chargeoff_within_12_mths,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
delinq_amnt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pub_rec_bankruptcies,-0.009505,-0.008769,-0.037180,-0.038502,-0.042746,-0.034103,-0.016801,0.005691,0.003375,0.016346,...,-0.004651,-0.005208,-0.022585,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
tax_liens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
loanData.drop(columns=['tax_liens','delinq_amnt','chargeoff_within_12_mths','acc_now_delinq','policy_code','collections_12_mths_ex_med'],axis=1,inplace=True)

In [33]:
loanData.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'pymnt_plan', 'desc', 'purpose', 'title',
       'zip_code', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record',
       'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'last_credit_pull_d',
       'application_type', 'pub_rec_bankruptcies', 'emp_length_range'],
      dtype='object')

In [34]:
loanData.corr()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,...,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,pub_rec_bankruptcies
id,1.000000,0.993650,0.141919,0.152286,0.249547,0.086587,0.008731,0.095983,-0.008644,-0.042378,...,0.180591,0.140045,0.220838,0.112213,0.172856,-0.055082,0.033426,-0.013359,0.122365,-0.009505
member_id,0.993650,1.000000,0.140710,0.150322,0.257887,0.081025,0.009380,0.096963,-0.008119,-0.047086,...,0.170706,0.139975,0.229307,0.112168,0.173234,-0.057750,0.031565,-0.015155,0.123627,-0.008769
loan_amnt,0.141919,0.140710,1.000000,0.981578,0.940034,0.930288,0.271149,0.066439,-0.031864,0.009229,...,0.192623,0.886613,0.854243,0.852021,0.729726,0.044706,0.135446,0.072853,0.448742,-0.037180
funded_amnt,0.152286,0.150322,0.981578,1.000000,0.958422,0.956159,0.266965,0.066283,-0.032355,0.009259,...,0.194675,0.903160,0.870799,0.870255,0.737469,0.046705,0.136284,0.074676,0.453133,-0.038502
funded_amnt_inv,0.249547,0.257887,0.940034,0.958422,1.000000,0.905039,0.254375,0.074689,-0.038501,-0.005712,...,0.203693,0.881228,0.913257,0.845848,0.730914,0.027172,0.123759,0.060358,0.442604,-0.042746
installment,0.086587,0.081025,0.930288,0.956159,0.905039,1.000000,0.270874,0.054186,-0.019657,0.009722,...,0.124932,0.856928,0.817416,0.850773,0.634725,0.056709,0.118152,0.075467,0.401688,-0.034103
annual_inc,0.008731,0.009380,0.271149,0.266965,0.254375,0.270874,1.000000,-0.122732,0.023083,0.033908,...,0.033472,0.257980,0.247119,0.259571,0.185476,0.006243,0.021589,0.015604,0.140401,-0.016801
dti,0.095983,0.096963,0.066439,0.066283,0.074689,0.054186,-0.122732,1.000000,-0.034452,0.001405,...,0.036012,0.064766,0.071647,0.041316,0.106071,-0.011781,0.024878,0.011033,0.005212,0.005691
delinq_2yrs,-0.008644,-0.008119,-0.031864,-0.032355,-0.038501,-0.019657,0.023083,-0.034452,1.000000,0.008091,...,-0.003203,-0.022695,-0.028976,-0.038795,0.023077,0.030609,0.012315,0.013912,-0.012149,0.003375
inq_last_6mths,-0.042378,-0.047086,0.009229,0.009259,-0.005712,0.009722,0.033908,0.001405,0.008091,1.000000,...,-0.011780,-0.010559,-0.020277,-0.023433,0.021774,0.031215,0.018972,0.012420,0.028514,0.016346
mths_since_last_delinq,0.117193,0.122963,0.014871,0.016359,0.071924,0.000047,-0.008822,0.068815,-0.569438,-0.003851,...,0.005501,0.012174,0.057515,0.015708,0.002801,-0.028460,-0.008622,-0.018697,0.007023,0.025841
mths_since_last_record,0.702130,0.719538,0.004968,-0.006059,0.437906,-0.062171,-0.031866,0.187175,-0.036628,-0.027878,...,0.056635,0.004355,0.373132,-0.041470,0.128281,-0.097503,-0.013125,-0.038484,0.078624,0.823352
open_acc,0.020388,0.017928,0.177168,0.175530,0.163027,0.172812,0.158200,0.288045,0.011656,0.091713,...,0.028514,0.162663,0.152937,0.160631,0.124499,-0.018627,0.016396,0.006219,0.078865,0.005930
pub_rec,-0.019440,-0.018721,-0.051236,-0.052169,-0.053214,-0.046532,-0.018689,-0.004621,0.007463,0.024802,...,-0.012910,-0.053668,-0.054101,-0.065384,-0.007470,-0.002071,-0.005521,-0.005536,-0.032214,0.847305
revol_bal,0.008763,0.005113,0.317597,0.310392,0.290797,0.312679,0.279961,0.228743,-0.055125,-0.022381,...,0.060183,0.293204,0.277543,0.281419,0.243000,0.003823,0.042091,0.022400,0.120371,-0.049406
total_acc,0.042149,0.044374,0.256442,0.250589,0.242854,0.230824,0.235771,0.229881,0.067892,0.111499,...,0.031009,0.225077,0.219244,0.231242,0.147792,-0.024715,0.023281,0.010551,0.162841,-0.011807
out_prncp,0.180619,0.170743,0.192937,0.194941,0.203688,0.125082,0.033573,0.036095,-0.003008,-0.012106,...,0.999827,0.239367,0.246537,0.166519,0.383746,-0.004644,-0.018878,-0.011394,-0.066393,-0.010024
out_prncp_inv,0.180591,0.170706,0.192623,0.194675,0.203693,0.124932,0.033472,0.036012,-0.003203,-0.011780,...,1.000000,0.239049,0.246524,0.166235,0.383410,-0.004752,-0.018858,-0.011382,-0.066324,-0.010314
total_pymnt,0.140045,0.139975,0.886613,0.903160,0.881228,0.856928,0.257980,0.064766,-0.022695,-0.010559,...,0.239049,1.000000,0.970815,0.971472,0.828758,0.012981,0.023950,0.024555,0.474624,-0.043661
total_pymnt_inv,0.220838,0.229307,0.854243,0.870799,0.913257,0.817416,0.247119,0.071647,-0.028976,-0.020277,...,0.246524,0.970815,1.000000,0.939581,0.815615,-0.000796,0.017862,0.015016,0.462255,-0.047011
total_rec_prncp,0.112213,0.112168,0.852021,0.870255,0.845848,0.850773,0.259571,0.041316,-0.038795,-0.023433,...,0.166235,0.971472,0.939581,1.000000,0.684027,-0.019667,-0.094821,-0.058634,0.543408,-0.054125
total_rec_int,0.172856,0.173234,0.729726,0.737469,0.730914,0.634725,0.185476,0.106071,0.023077,0.021774,...,0.383410,0.828758,0.815615,0.684027,1.000000,0.069099,0.075552,0.033289,0.191990,-0.003609
total_rec_late_fee,-0.055082,-0.057750,0.044706,0.046705,0.027172,0.056709,0.006243,-0.011781,0.030609,0.031215,...,-0.004752,0.012981,-0.000796,-0.019667,0.069099,1.000000,0.099925,0.093178,-0.060600,-0.005489
recoveries,0.033426,0.031565,0.135446,0.136284,0.123759,0.118152,0.021589,0.024878,0.012315,0.018972,...,-0.018858,0.023950,0.017862,-0.094821,0.075552,0.099925,1.000000,0.796816,-0.069955,-0.004651
collection_recovery_fee,-0.013359,-0.015155,0.072853,0.074676,0.060358,0.075467,0.015604,0.011033,0.013912,0.012420,...,-0.011382,0.024555,0.015016,-0.058634,0.033289,0.093178,0.796816,1.000000,-0.041874,-0.005208
last_pymnt_amnt,0.122365,0.123627,0.448742,0.453133,0.442604,0.401688,0.140401,0.005212,-0.012149,0.028514,...,-0.066324,0.474624,0.462255,0.543408,0.191990,-0.060600,-0.069955,-0.041874,1.000000,-0.022585
pub_rec_bankruptcies,-0.009505,-0.008769,-0.037180,-0.038502,-0.042746,-0.034103,-0.016801,0.005691,0.003375,0.016346,...,-0.010314,-0.043661,-0.047011,-0.054125,-0.003609,-0.005489,-0.004651,-0.005208,-0.022585,1.000000

   ### loan Data Univariate analysis

###### Arpita : Start : 31/01/2019

In [36]:
loanData.to_csv('loanData_afterCleaning.csv', sep=',')

In [ ]:
pd.pivot_table(loanData, index=['annual_inc'], values=['member_id'],aggfunc=np.sum)

In [42]:
pd.pivot_table(loanData, index=['pub_rec_bankruptcies'], values=['member_id'],aggfunc=len)

                      member_id
pub_rec_bankruptcies
0.0                     37339.0
1.0                      1674.0
2.0                         7.0

### Filter the customers whose loan status is either 'Current' or 'Charged Off'

In [57]:
loanDataCurrent_ChargedOff = loanData.loc[(loanData['loan_status']=='Charged Off') | (loanData['loan_status']=='Current')]
loanDataCurrent_ChargedOff.to_csv('loanData_onlyCurrentAndChargedOff.csv')

### Filter the customers whose loan status is Charged Off

In [43]:
pd.pivot_table(loanData, index=['loan_status'], values=['member_id'],aggfunc=len)

             member_id
loan_status
Charged Off     5627.0
Current         1140.0
Fully Paid     32950.0

In [44]:
loanDataChargedOff = loanData.loc[loanData['loan_status']=='Charged Off']

In [48]:
loanDataChargedOff.head(10)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,application_type,pub_rec_bankruptcies,emp_length_range
1,1077430.0,1314167.0,2500.0,2500.0,2500.0,60 months,15.27%,59.83,C,C4,...,435.17,0.0,117.08,1.1100,Apr-13,119.66,Sep-13,INDIVIDUAL,0.0,0 years
8,1071795.0,1306957.0,5600.0,5600.0,5600.0,60 months,21.28%,152.39,F,F2,...,294.94,0.0,189.06,2.0900,Apr-12,152.39,Aug-12,INDIVIDUAL,0.0,0-10 years
9,1071570.0,1306721.0,5375.0,5375.0,5350.0,60 months,12.69%,121.45,B,B5,...,533.42,0.0,269.29,2.5200,Nov-12,121.45,Mar-13,INDIVIDUAL,0.0,0 years
12,1064687.0,1298717.0,9000.0,9000.0,9000.0,36 months,13.49%,305.38,C,C1,...,570.26,0.0,444.30,4.1600,Jul-12,305.38,Nov-12,INDIVIDUAL,0.0,0 years
14,1069057.0,1303503.0,10000.0,10000.0,10000.0,36 months,10.65%,325.74,B,B2,...,1393.42,0.0,645.10,6.3145,Oct-13,325.74,Mar-14,INDIVIDUAL,0.0,0-10 years
21,1039153.0,1269083.0,21000.0,21000.0,21000.0,36 months,12.42%,701.73,B,B4,...,3330.44,0.0,0.00,0.0000,Sep-13,701.73,May-16,INDIVIDUAL,0.0,10+ years
24,1069559.0,1304634.0,6000.0,6000.0,6000.0,36 months,11.71%,198.46,B,B3,...,475.25,0.0,269.31,2.5700,Oct-12,198.46,Mar-13,INDIVIDUAL,0.0,0-10 years
26,1069800.0,1304679.0,15000.0,15000.0,8725.0,36 months,14.27%,514.64,C,C2,...,0.00,0.0,0.00,0.0000,NaN,0.00,May-16,INDIVIDUAL,0.0,0-10 years
27,1069657.0,1304764.0,5000.0,5000.0,5000.0,60 months,16.77%,123.65,D,D2,...,719.11,0.0,260.96,2.3000,Dec-12,123.65,May-13,INDIVIDUAL,0.0,0-10 years
46,1069465.0,1304521.0,5000.0,5000.0,5000.0,36 months,8.90%,158.77,A,A5,...,696.99,0.0,107.00,1.0700,Aug-14,158.77,Dec-14,INDIVIDUAL,0.0,10+ years

### No. of Charged-Off cases with derogatory public records

In [49]:
pd.pivot_table(loanDataChargedOff, index=['pub_rec'], values=['member_id'],aggfunc=len)

         member_id
pub_rec
0.0         5160.0
1.0          457.0
2.0           10.0

### No. of Charged-Off cases with credit inquiries in last 6 months

In [52]:
temp_df = pd.pivot_table(loanDataChargedOff, index=['inq_last_6mths'], values=['member_id'],aggfunc=len)
temp_df.sort_values(by='inq_last_6mths', ascending=False)

                member_id
inq_last_6mths
8.0                   3.0
7.0                  10.0
6.0                  16.0
5.0                  28.0
4.0                  51.0
3.0                 619.0
2.0                 943.0
1.0                1677.0
0.0                2280.0

In [53]:
## List of members with loan status 'Charged-off' having max. credit inquiries (8) in last 6 months
loanDataChargedOff.loc[loanDataChargedOff['inq_last_6mths']==8]

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,application_type,pub_rec_bankruptcies,emp_length_range
2567,1034529.0,1264348.0,14000.0,14000.0,14000.000000,36 months,14.65%,482.92,C,C3,...,1261.05,0.0,0.00,0.00,Aug-12,965.84,May-16,INDIVIDUAL,0.0,10+ years
13794,775726.0,962280.0,25000.0,25000.0,24975.000000,60 months,21.74%,686.79,F,F5,...,8526.09,0.0,1095.45,10.51,Apr-13,42.54,Aug-13,INDIVIDUAL,0.0,10+ years
39215,239843.0,239780.0,20000.0,20000.0,1325.001135,36 months,9.51%,640.76,B,B2,...,2514.68,0.0,0.00,0.00,Dec-09,640.76,Apr-16,INDIVIDUAL,NaN,10+ years

### Are there any member_ids with Charged-off loan status that are duplicated?

In [60]:
loanDataChargedOff_memberids = loanDataChargedOff['member_id']
loanDataChargedOff[loanDataChargedOff_memberids.isin(loanDataChargedOff_memberids[loanDataChargedOff_memberids.duplicated()])]

Empty DataFrame
Columns: [id, member_id, loan_amnt, funded_amnt, funded_amnt_inv, term, int_rate, installment, grade, sub_grade, emp_title, emp_length, home_ownership, annual_inc, verification_status, issue_d, loan_status, pymnt_plan, desc, purpose, title, zip_code, addr_state, dti, delinq_2yrs, earliest_cr_line, inq_last_6mths, mths_since_last_delinq, mths_since_last_record, open_acc, pub_rec, revol_bal, revol_util, total_acc, initial_list_status, out_prncp, out_prncp_inv, total_pymnt, total_pymnt_inv, total_rec_prncp, total_rec_int, total_rec_late_fee, recoveries, collection_recovery_fee, last_pymnt_d, last_pymnt_amnt, last_credit_pull_d, application_type, pub_rec_bankruptcies, emp_length_range]
Index: []

[0 rows x 50 columns]

###### Arpita : End : 31/01/2019